
development:
  adapter: postgresql
  encoding: utf8
  database: table_maker_development
  pool: 5
  username: postgres
  password: test
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: table_maker_test
  pool: 5
  username: postgres
  password: test
  host: localhost
